apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: stable
    meta.helm.sh/release-namespace: prometheus
  creationTimestamp: "2024-03-27T20:41:40Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: stable
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 10.4.0
    helm.sh/chart: grafana-7.3.7
  name: stable-grafana
  namespace: prometheus
  resourceVersion: "79957429"
  uid: 30d55fdf-9b52-48aa-a3ad-d61728818b65
spec:
  endpoints:
  - honorLabels: true
    path: /metrics
    port: http-web
    scheme: http
    scrapeTimeout: 30s
  jobLabel: stable
  namespaceSelector:
    matchNames:
    - prometheus
  selector:
    matchLabels:
      app.kubernetes.io/instance: stable
      app.kubernetes.io/name: grafana
