apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: node-exporter
    release: stable  # Matches the Helm release name
  name: stable-kube-prometheus-sta-prometheus-node-exporter
  namespace: prometheus
spec:
  endpoints:
    - interval: 30s
      port: metrics
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: node-exporter
      app.kubernetes.io/instance: stable
